services:
  frontend:
    build:
      context: .
      dockerfile: services/frontend/Dockerfile
      args:
        NODE_VERSION: 20.11.1
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=backend:8080
    restart: unless-stopped

  backend:
    build:
      context: services/backend
      dockerfile: Dockerfile
      args:
        GO_VERSION: 1.23
    ports:
      - "8080:8080"
    volumes:
      - sqlite_data:/app/data
    environment:
      - SQLITE_DB_PATH=/app/data/myapp.db
    env_file:
      - services/backend/.env
    restart: unless-stopped

volumes:
  sqlite_data:
